import { Geist, Geist_Mono } from "next/font/google";
import "@/app/_style/globals.css";
import Header from "./_components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "%s / Potofilo",
    default: "welcome / Portofilo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-350 px-5 mx-auto bg-zinc-950">
        <Header />
        {children}
      </body>
    </html>
  );
}
