import "./_style/globals.css";
import Header from "./_components/Header";
import Baloo_Bhaijaan_2 from "next/font/local";
import Footer from "./_components/Footer";

const baloo = Baloo_Bhaijaan_2({
  // subsets: ["arabic"],
  // weight: ["400", "500", "600", "700", "800"],
  // display: "swap",
  src: [
    {
      path: "../public/fonts/BalooBhaijaan2-Medium.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: {
    template: "%s / Potofilo",
    default: "welcome / Portofilo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-black ${baloo.className}`}>
        <div className="max-w-320 px-5 mx-auto">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
